version: "3.2"
volumes:
  gems:
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=res-ecommerce
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
