source "https://rubygems.org"

ruby "3.1.0"

gem "bootsnap", ">= 1.4.4", require: false
gem "capture_migration_sql", "~>1.0.2"
gem "honeybadger", "~> 4.0"
gem "kaminari"
gem "pg", "~> 1.1"
gem "puma", "~> 5.6"
gem "rails", "~> 7.0.2", ">= 7.0.2.2"
gem "skylight"
gem "sprockets-rails"
gem "tailwindcss-rails"

group :development do
  gem "listen", "~> 3.3"
end

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "dotenv-rails"
end

group :test do
  eval_gemfile "../infra/Gemfile.test"
end

gem "infra", path: "../infra"
gem "math", path: "../math"

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
